#!/usr/bin/env python3
"""Export trained G2P checkpoint to C header files for ESP32 inference.

Usage:
    uv run tiny-renikud/scripts/export_weights.py <checkpoint_dir_or_safetensors> [--quantize]

Outputs:
    tiny-renikud/src/weights.h      — weight arrays (float32 or int8 + scales)
    tiny-renikud/src/model_config.h — vocab, label tables, letter constraints
"""

from __future__ import annotations

import argparse
import io
import sys
import unicodedata
from pathlib import Path

import numpy as np
import torch

# Allow imports from src/
REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from phonology import ID_TO_CONSONANT, ID_TO_VOWEL, HEBREW_LETTER_CONSONANT_IDS
from tokenization import build_vocab


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_state_dict(path: Path) -> dict[str, torch.Tensor]:
    if path.is_dir():
        path = path / "model.safetensors"
    if path.suffix == ".safetensors":
        from safetensors.torch import load_file
        return load_file(str(path))
    return torch.load(str(path), map_location="cpu")


def to_c_name(py_name: str) -> str:
    return py_name.replace(".", "_").replace("-", "_")


def write_float_array(buf: io.StringIO, name: str, data: np.ndarray) -> None:
    flat = data.flatten().astype(np.float32)
    buf.write(f"static const float {name}[{flat.size}] = {{\n")
    for i, v in enumerate(flat):
        buf.write(f"  {v:.8e}f,")
        if (i + 1) % 8 == 0:
            buf.write("\n")
    buf.write("\n};\n\n")


def write_int8_array(buf: io.StringIO, name: str, data: np.ndarray) -> tuple[float, float]:
    """Quantize to int8 symmetric, return (scale, zero_point=0)."""
    flat = data.flatten().astype(np.float32)
    amax = np.abs(flat).max()
    scale = float(amax) / 127.0 if amax > 0 else 1.0
    quantized = np.clip(np.round(flat / scale), -127, 127).astype(np.int8)
    buf.write(f"static const int8_t {name}[{quantized.size}] = {{\n")
    for i, v in enumerate(quantized):
        buf.write(f"  {int(v)},")
        if (i + 1) % 16 == 0:
            buf.write("\n")
    buf.write("\n};\n\n")
    return scale


def emit_weight(buf: io.StringIO, scales_buf: io.StringIO, name: str,
                tensor: torch.Tensor, quantize: bool) -> None:
    data = tensor.detach().float().numpy()
    if quantize and data.ndim >= 2:  # quantize matrices, keep biases as float
        scale = write_int8_array(buf, name, data)
        scales_buf.write(f"static const float {name}_scale = {scale:.8e}f;\n")
    else:
        write_float_array(buf, name, data)


# ---------------------------------------------------------------------------
# weights.h
# ---------------------------------------------------------------------------

def export_weights(state: dict[str, torch.Tensor], quantize: bool) -> str:
    buf = io.StringIO()
    scales_buf = io.StringIO()

    buf.write("#pragma once\n")
    buf.write("// Auto-generated by export_weights.py — do not edit\n\n")
    buf.write('#include <stdint.h>\n\n')

    def w(key: str, c_name: str) -> None:
        t = state[key]
        emit_weight(buf, scales_buf, c_name, t, quantize)

    # Embeddings
    w("encoder.embeddings.word_embeddings.weight",     "emb_word")
    w("encoder.embeddings.position_embeddings.weight", "emb_pos")
    w("encoder.embeddings.token_type_embeddings.weight","emb_type")
    w("encoder.embeddings.LayerNorm.weight",            "emb_ln_w")
    w("encoder.embeddings.LayerNorm.bias",              "emb_ln_b")

    # Transformer layers
    for i in range(3):
        p = f"encoder.encoder.layer.{i}"
        li = f"layer{i}"
        w(f"{p}.attention.self.query.weight",    f"{li}_q_w")
        w(f"{p}.attention.self.query.bias",      f"{li}_q_b")
        w(f"{p}.attention.self.key.weight",      f"{li}_k_w")
        w(f"{p}.attention.self.key.bias",        f"{li}_k_b")
        w(f"{p}.attention.self.value.weight",    f"{li}_v_w")
        w(f"{p}.attention.self.value.bias",      f"{li}_v_b")
        w(f"{p}.attention.output.dense.weight",  f"{li}_attn_out_w")
        w(f"{p}.attention.output.dense.bias",    f"{li}_attn_out_b")
        w(f"{p}.attention.output.LayerNorm.weight", f"{li}_attn_ln_w")
        w(f"{p}.attention.output.LayerNorm.bias",   f"{li}_attn_ln_b")
        w(f"{p}.intermediate.dense.weight",      f"{li}_ffn1_w")
        w(f"{p}.intermediate.dense.bias",        f"{li}_ffn1_b")
        w(f"{p}.output.dense.weight",            f"{li}_ffn2_w")
        w(f"{p}.output.dense.bias",              f"{li}_ffn2_b")
        w(f"{p}.output.LayerNorm.weight",        f"{li}_ffn_ln_w")
        w(f"{p}.output.LayerNorm.bias",          f"{li}_ffn_ln_b")

    # Classification heads (always float — small, and avoids scale complexity at output)
    w("consonant_head.weight", "head_consonant_w")
    w("consonant_head.bias",   "head_consonant_b")
    w("vowel_head.weight",     "head_vowel_w")
    w("vowel_head.bias",       "head_vowel_b")
    w("stress_head.weight",    "head_stress_w")
    w("stress_head.bias",      "head_stress_b")

    # Append scales after all arrays
    scales = scales_buf.getvalue()
    if scales:
        buf.write("// Per-tensor quantization scales\n")
        buf.write(scales)

    return buf.getvalue()


# ---------------------------------------------------------------------------
# model_config.h
# ---------------------------------------------------------------------------

def escape_utf8(s: str) -> str:
    """Encode a unicode string as a C string literal with hex escapes."""
    encoded = s.encode("utf-8")
    return "".join(f"\\x{b:02x}" for b in encoded)


def export_config() -> str:
    vocab = build_vocab()
    buf = io.StringIO()

    buf.write("#pragma once\n")
    buf.write("// Auto-generated by export_weights.py — do not edit\n\n")
    buf.write('#include <stdint.h>\n\n')

    # Model dimensions
    buf.write("#define HIDDEN_SIZE       96\n")
    buf.write("#define NUM_HEADS         4\n")
    buf.write("#define HEAD_DIM          24\n")
    buf.write("#define NUM_LAYERS        3\n")
    buf.write("#define INTERMEDIATE_SIZE 192\n")
    buf.write("#define VOCAB_SIZE        104\n")
    buf.write("#define MAX_SEQ_LEN       512\n")
    buf.write("#define NUM_CONSONANTS    25\n")
    buf.write("#define NUM_VOWELS        6\n")
    buf.write("#define NUM_STRESS        2\n")
    buf.write("#define CLS_TOKEN_ID      1\n")
    buf.write("#define SEP_TOKEN_ID      2\n")
    buf.write("#define PAD_TOKEN_ID      0\n")
    buf.write("#define UNK_TOKEN_ID      3\n\n")

    # Vocab: unicode codepoint → token id
    # Represented as a sorted array of (codepoint, id) pairs for binary search
    # Filter to single-char keys only (skip special tokens like [CLS])
    char_entries = [(ord(ch), tid) for ch, tid in vocab.items() if len(ch) == 1]
    char_entries.sort()
    buf.write(f"// {len(char_entries)} single-character vocab entries, sorted by codepoint\n")
    buf.write(f"#define VOCAB_CHAR_COUNT {len(char_entries)}\n")
    buf.write("static const uint32_t VOCAB_CODEPOINTS[VOCAB_CHAR_COUNT] = {\n  ")
    buf.write(", ".join(str(cp) for cp, _ in char_entries))
    buf.write("\n};\n")
    buf.write("static const uint8_t VOCAB_TOKEN_IDS[VOCAB_CHAR_COUNT] = {\n  ")
    buf.write(", ".join(str(tid) for _, tid in char_entries))
    buf.write("\n};\n\n")

    # Consonant labels (UTF-8 string table)
    buf.write("// IPA consonant labels indexed by consonant class id\n")
    buf.write("static const char* CONSONANT_LABELS[NUM_CONSONANTS] = {\n")
    for i in range(25):
        label = ID_TO_CONSONANT[i]
        buf.write(f'  "{escape_utf8(label)}",  // {i}: {label}\n')
    buf.write("};\n\n")

    # Vowel labels
    buf.write("static const char* VOWEL_LABELS[NUM_VOWELS] = {\n")
    for i in range(6):
        label = ID_TO_VOWEL[i]
        buf.write(f'  "{escape_utf8(label)}",  // {i}: {label}\n')
    buf.write("};\n\n")

    # Letter constraints: for each Hebrew letter, which consonant ids are allowed
    # Format: flat array + offset/length table
    hebrew_letters = [chr(cp) for cp, _ in char_entries if ord('א') <= cp <= ord('ת')]
    buf.write("// Per-letter consonant constraints\n")
    buf.write(f"#define NUM_HEBREW_LETTERS {len(hebrew_letters)}\n")

    flat_ids: list[int] = []
    offsets: list[tuple[int, int]] = []  # (offset, length)
    letter_codepoints: list[int] = []

    for letter in hebrew_letters:
        allowed = HEBREW_LETTER_CONSONANT_IDS.get(letter)
        letter_codepoints.append(ord(letter))
        if allowed is None:
            offsets.append((len(flat_ids), 0))
        else:
            offsets.append((len(flat_ids), len(allowed)))
            flat_ids.extend(allowed)

    buf.write("static const uint32_t HEBREW_LETTER_CODEPOINTS[NUM_HEBREW_LETTERS] = {\n  ")
    buf.write(", ".join(str(cp) for cp in letter_codepoints))
    buf.write("\n};\n")
    buf.write(f"static const uint8_t CONSTRAINT_IDS[{len(flat_ids)}] = {{\n  ")
    buf.write(", ".join(str(x) for x in flat_ids))
    buf.write("\n};\n")
    buf.write("static const uint8_t CONSTRAINT_OFFSET[NUM_HEBREW_LETTERS] = {\n  ")
    buf.write(", ".join(str(o) for o, _ in offsets))
    buf.write("\n};\n")
    buf.write("static const uint8_t CONSTRAINT_LEN[NUM_HEBREW_LETTERS] = {\n  ")
    buf.write(", ".join(str(l) for _, l in offsets))
    buf.write("\n};\n")

    return buf.getvalue()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Export G2P weights to C headers")
    parser.add_argument("checkpoint", type=Path, help="Path to checkpoint dir or model.safetensors")
    parser.add_argument("--quantize", action="store_true", help="Quantize weight matrices to int8")
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "tiny-renikud" / "src",
                        help="Output directory (default: tiny-renikud/src/)")
    args = parser.parse_args()

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading checkpoint from {args.checkpoint} ...")
    state = load_state_dict(args.checkpoint)
    print(f"  {len(state)} tensors loaded")

    mode = "int8" if args.quantize else "float32"
    print(f"Exporting weights ({mode}) ...")
    weights_h = export_weights(state, args.quantize)
    weights_path = out_dir / "weights.h"
    weights_path.write_text(weights_h)
    size_kb = weights_path.stat().st_size / 1024
    print(f"  -> {weights_path}  ({size_kb:.1f} KB)")

    print("Exporting model config ...")
    config_h = export_config()
    config_path = out_dir / "model_config.h"
    config_path.write_text(config_h)
    print(f"  -> {config_path}")

    print("Done.")


if __name__ == "__main__":
    main()
