#pragma once
// Auto-generated by export_weights.py — do not edit

#include <stdint.h>

#define HIDDEN_SIZE       96
#define NUM_HEADS         4
#define HEAD_DIM          24
#define NUM_LAYERS        3
#define INTERMEDIATE_SIZE 192
#define VOCAB_SIZE        104
#define MAX_SEQ_LEN       512
#define NUM_CONSONANTS    25
#define NUM_VOWELS        6
#define NUM_STRESS        2
#define CLS_TOKEN_ID      1
#define SEP_TOKEN_ID      2
#define PAD_TOKEN_ID      0
#define UNK_TOKEN_ID      3

// 99 single-character vocab entries, sorted by codepoint
#define VOCAB_CHAR_COUNT 99
static const uint32_t VOCAB_CODEPOINTS[VOCAB_CHAR_COUNT] = {
  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 1470, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1523, 1524
};
static const uint8_t VOCAB_TOKEN_IDS[VOCAB_CHAR_COUNT] = {
  73, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 69, 70, 71, 72, 101, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 102, 103
};

// IPA consonant labels indexed by consonant class id
static const char* CONSONANT_LABELS[NUM_CONSONANTS] = {
  "\xe2\x88\x85",  // 0: ∅
  "\x62",  // 1: b
  "\x76",  // 2: v
  "\x64",  // 3: d
  "\x68",  // 4: h
  "\x7a",  // 5: z
  "\xcf\x87",  // 6: χ
  "\x74",  // 7: t
  "\x6a",  // 8: j
  "\x6b",  // 9: k
  "\x6c",  // 10: l
  "\x6d",  // 11: m
  "\x6e",  // 12: n
  "\x73",  // 13: s
  "\x66",  // 14: f
  "\x70",  // 15: p
  "\x74\x73",  // 16: ts
  "\x74\xca\x83",  // 17: tʃ
  "\x77",  // 18: w
  "\xca\x94",  // 19: ʔ
  "\xc9\xa1",  // 20: ɡ
  "\xca\x81",  // 21: ʁ
  "\xca\x83",  // 22: ʃ
  "\xca\x92",  // 23: ʒ
  "\x64\xca\x92",  // 24: dʒ
};

static const char* VOWEL_LABELS[NUM_VOWELS] = {
  "\xe2\x88\x85",  // 0: ∅
  "\x61",  // 1: a
  "\x65",  // 2: e
  "\x69",  // 3: i
  "\x6f",  // 4: o
  "\x75",  // 5: u
};

// Per-letter consonant constraints
#define NUM_HEBREW_LETTERS 27
static const uint32_t HEBREW_LETTER_CODEPOINTS[NUM_HEBREW_LETTERS] = {
  1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514
};
static const uint8_t CONSTRAINT_IDS[45] = {
  19, 0, 1, 2, 20, 24, 3, 4, 0, 2, 18, 0, 5, 23, 6, 7, 8, 0, 9, 6, 9, 6, 10, 0, 11, 11, 12, 12, 13, 19, 0, 15, 14, 15, 14, 16, 17, 16, 17, 9, 21, 22, 13, 0, 7
};
static const uint8_t CONSTRAINT_OFFSET[NUM_HEBREW_LETTERS] = {
  0, 2, 4, 6, 7, 9, 12, 14, 15, 16, 18, 20, 22, 24, 25, 26, 27, 28, 29, 31, 33, 35, 37, 39, 40, 41, 44
};
static const uint8_t CONSTRAINT_LEN[NUM_HEBREW_LETTERS] = {
  2, 2, 2, 1, 2, 3, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 3, 1
};
